### ISSUE TITLE
Enable travis-ci or circle-ci continuous integration service

### ISSUE THREAD

**Issue by PeterDaveHello** [SummerWish/express-minify#23]
Cause we already have test functions, it's very very easy to setup ci integration, it'll help keep the code work, especially it can test each pull request automatically!

Would you like to add it?

**Comment by SummerWish** [comment]
wow. lightning speed :-)
I have already added travis ci config files so I will close this issue and the PR.

**Comment by PeterDaveHello** [comment]
Don't you want the badge in #29?
