### ISSUE TITLE
What's the reason why to remove blacklist support?

### ISSUE THREAD

**Issue by PeterDaveHello** [SummerWish/express-minify#35]
Hi @SummerWish,

I think it's really useful, don't know if there is special reason to remove it?

Cause I found that if the json file be two large, the works will be locked, I need to ignore them ...

Thanks ...

**Comment by SummerWish** [comment]
Hi,

it is replaced by a more flexable feature: `res._skip`.

for example:

```js
app.use(function(req, res, next)
{
    if (req.url.indexOf('my-last-file.js')) {   // you can write more complex logic here
        res._skip = true;
    }
    next();
});
app.use(minify());
```

**Comment by PeterDaveHello** [comment]
oh ... okay ...
maybe we don't need a complex and flexable for all time xD

**Comment by SummerWish** [comment]
LOL make full use of the middleware concept :-) you can write much more complex logic here, blacklists are no longer limited to an regular expression.
