### ISSUE TITLE
stylus not required when not loaded yet

### ISSUE THREAD

**Issue by faeb187** [SummerWish/express-minify#40]
**VERSIONS** nodeJS: 4.0.0, expressJS: 4.13.3

I just updated to the latest nodeJS and expressJS versions and express-minify didn't compile my text/stylus responses anymore.

Reading your code I found out that the variable stylus is false BUT require( "stylus" ) never happens.

**WORKAROUND** I preinstalled the latest stylus now and everything fine again.

**THOUGHTS** Not invested that much time but maybe your minifyIt() is only called when caching activated?

**Comment by SummerWish** [comment]
Hi, in the latest version you need to manually download stylus dependency in order to use stylus compiling.

https://github.com/SummerWish/express-minify#parse-and-minify-coffeescriptlesssassstylus

**Comment by SummerWish** [comment]
Issue closed because of no further feedbacks. If this issue still exists please leave a comment.
